/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for Wav2Bar settings, version 2. (For versions 1.0.0-beta.1 and above).
 *
 *  Wav2Bar - Free software for creating audio visualization (motion design) videos.
 *  Copyright (C) 2025-2026  Picorims <picorims.contact@gmail.com>
 *
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
export interface Wav2BarSettingsV2 {
	save_version: 2;
	/**
	 * last version modifying this settings file
	 */
	software_version_used: string;
	/**
	 * first version creating this settings file
	 */
	software_version_first_created: string;
	ffmpeg_path: string;
	theme: 'DEFAULT' | 'DARK' | 'LIGHT';
	language: 'EN';
	[k: string]: unknown;
}
